// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL6OCBnhgZs7KK0hzXLGQ5qy_EQzj_45k',
    appId: '1:1064523168761:web:6a4cce72ab0956bbaddb28',
    messagingSenderId: '1064523168761',
    projectId: 'bkash-dso-calculator',
    authDomain: 'bkash-dso-calculator.firebaseapp.com',
    storageBucket: 'bkash-dso-calculator.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBSL_FTJlQ3NSPnyeYh55YrAoeWCQ6MiY',
    appId: '1:1064523168761:android:77b765f288f4a30daddb28',
    messagingSenderId: '1064523168761',
    projectId: 'bkash-dso-calculator',
    storageBucket: 'bkash-dso-calculator.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Rl_ItzgdOqge8vj80cmd2xcnghyzNYM',
    appId: '1:1064523168761:ios:d43d1f42779dadb4addb28',
    messagingSenderId: '1064523168761',
    projectId: 'bkash-dso-calculator',
    storageBucket: 'bkash-dso-calculator.appspot.com',
    iosClientId: '1064523168761-o097e5neglce4hmen87iu52dj17ferk4.apps.googleusercontent.com',
    iosBundleId: 'com.bkash.bkashdsocalculator.bkashdsocalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Rl_ItzgdOqge8vj80cmd2xcnghyzNYM',
    appId: '1:1064523168761:ios:d43d1f42779dadb4addb28',
    messagingSenderId: '1064523168761',
    projectId: 'bkash-dso-calculator',
    storageBucket: 'bkash-dso-calculator.appspot.com',
    iosClientId: '1064523168761-o097e5neglce4hmen87iu52dj17ferk4.apps.googleusercontent.com',
    iosBundleId: 'com.bkash.bkashdsocalculator.bkashdsocalculator',
  );
}
